# Train a many-to-English multilingual model from the already projected
# synthetic 16-language data and evaluate on reversed English-source BOUQuET
# dev data.

export LANGS SRCLANGS TRGLANGS LANGPAIRSTR
export DATASET TRAINSET
export DEVSET DEVSET_NAME DEV_SRCLANGS DEV_TRGLANGS KEEP_FULL_DEVSET
export TESTSET TESTSET_NAME TEST_SRCLANGS TEST_TRGLANGS KEEP_FULL_TESTSET
export MODELTYPE PRE SUBWORDS CLEAN_TRAINDATA_TYPE CLEAN_DEVDATA_TYPE CLEAN_TESTDATA_TYPE
export SKIP_SAME_LANG SHUFFLE_DATA MAX_OVER_SAMPLING USE_REST_DEVDATA
export DEVSIZE TESTSIZE DEVMINSIZE SUBWORD_VOCAB_SIZE
export USE_TARGET_LABELS TARGET_LABELS
export MARIAN_VALID_METRICS MARIAN_VALID_FREQ MARIAN_MINI_BATCH MARIAN_MAXI_BATCH MARIAN_VALID_MINI_BATCH MARIAN_EXTRA MARIAN_WORKSPACE
export GPUJOB_HPC_MEM GPUJOB_SUBMIT

LANGS       = tr kmr de es fr el bg ru ka hy fa ar ckb ur
SRCLANGS    = ${LANGS}
TRGLANGS    = en
LANGPAIRSTR = synthetic-n2en-bouquet

DATASET  = synthetic_parallel_16lang_1_4m_gemini_3_1_flash_lite
TRAINSET = synthetic_parallel_16lang_1_4m_gemini_3_1_flash_lite

DEVSET   = bouquet-dev-n2en
DEVSET_NAME = bouquet-dev-n2en
DEV_SRCLANGS = ${LANGS}
DEV_TRGLANGS = en
KEEP_FULL_DEVSET = 1

TESTSET  = bouquet-dev-n2en
TESTSET_NAME = bouquet-dev-n2en
TEST_SRCLANGS = ${LANGS}
TEST_TRGLANGS = en
KEEP_FULL_TESTSET = 1

MODELTYPE = transformer
PRE       = simple
SUBWORDS  = spm
CLEAN_TRAINDATA_TYPE = clean
CLEAN_DEVDATA_TYPE = clean
CLEAN_TESTDATA_TYPE = clean

SKIP_SAME_LANG = 1
SHUFFLE_DATA = 1
MAX_OVER_SAMPLING = 50
USE_REST_DEVDATA = 1

DEVSIZE = 2500
TESTSIZE = 2500
DEVMINSIZE = 250

SUBWORD_VOCAB_SIZE = 32000

# Many-to-English still needs the target-language control token on source.
USE_TARGET_LABELS = 1
TARGET_LABELS = >>en<<

MARIAN_VALID_METRICS = bleu
MARIAN_VALID_FREQ = 26500u
MARIAN_MINI_BATCH = 2048
MARIAN_MAXI_BATCH = 4000
MARIAN_VALID_MINI_BATCH = 32
MARIAN_EXTRA += --mini-batch ${MARIAN_MINI_BATCH} --maxi-batch ${MARIAN_MAXI_BATCH}
MARIAN_WORKSPACE = 30000

GPUJOB_HPC_MEM = 16g
GPUJOB_SUBMIT =
